rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby

# Workaround for `NoMethodError: undefined method 'spec' for nil:NilClass`,
# see https://travis-ci.org/jmcnevin/rubypants/jobs/167182556
# and https://github.com/travis-ci/travis-ci/issues/5239
before_install:
  - gem install bundler

script:
  - bundle exec rake
